[project]
name = "temno"
version = "0.1.0"
description = "Explore Yasno API"
readme = "README.md"
requires-python = ">=3.13.1"
dependencies = [
    "pydantic>=2.10.4",
    "pytest>=8.3.4",
    "ruff>=0.8.4",
]
